### ISSUE TITLE
upkeep: remove superfluous manual setting of "production" -> 0

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.aggregate.loanbooks#74]
This is now handled in `r2dii.analysis` since https://github.com/RMI-PACTA/r2dii.analysis/pull/460

- [ ] https://github.com/RMI-PACTA/workflow.aggregate.loanbooks/blob/1b7121dd734946529ee3f19a131894594eeab035/run_pacta_in_bulk.R#L88
- [ ] https://github.com/RMI-PACTA/workflow.aggregate.loanbooks/blob/1b7121dd734946529ee3f19a131894594eeab035/run_aggregate_loanbooks.R#L87

**Comment by jacobvjk** [comment]
@jdhoffa I think this should only be removed when PACTA is actually run.

That is for:
- `run_pacta_in_bulk.R`
- `run_aggregate_loanbooks.R`

For scripts that do other analyses using the ABCD, we still need this. I would suggest adjusting the issue accordingly.

**Comment by jdhoffa** [comment]
Done
