### ISSUE TITLE
rename to `workflow.multi.loanbook`

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.aggregate.loanbooks#85]
new name `workflow.multi.loanbook` is consistent with naming convention for packages `pacta.multi.loanbook.analysis` and `pacta.multi.loanbook.plot` and thus a good name for the general P4S workflow

[AB#10188](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10188)

**Comment by jdhoffa** [comment]
Closed by https://github.com/RMI-PACTA/workflow.multi.loanbook/
